### ISSUE TITLE
If I want to Implement recognizer.py using the API with 3 function

### ISSUE THREAD

**Issue by Polarbeargo** [DoubangoTelecom/ultimateCreditCard-SDK#20] opened 2020-09-22 07:27 UTC
Hello @DoubangoTelecom,
If I want to Implement recognizer.py using the API with 3 functions: init, process, and deInit. Like mentioned in [SDK_TechnicalGuide_v2.0.pdf](https://github.com/DoubangoTelecom/ultimateCreditCard-SDK/blob/master/SDK_TechnicalGuide_v2.0.pdf) and [ultimateALPR-SDK](https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/samples/python), build the python extension. Is there anything else required for binding binaries?

**Comment by DoubangoTelecom** [comment] 2020-09-22 10:58
The c++ wrappers (like these at https://github.com/DoubangoTelecom/ultimateALPR-SDK/tree/master/python) are missing

Duplicate of #19

**Closed by DoubangoTelecom** 2020-09-22 10:58 UTC

**Comment by Polarbeargo** [comment] 2020-09-22 11:07
Thank you @DoubangoTelecom 👍 !
